# Generated by Django 3.0.5 on 2023-05-05 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230505_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 11, 5, 58, 508534)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 11, 5, 58, 508534)),
        ),
    ]
