# Generated by Django 3.0.5 on 2023-05-17 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20230505_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 11, 31, 5, 35986)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 11, 31, 5, 34448)),
        ),
    ]
