# Generated by Django 3.0.5 on 2023-05-17 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20230517_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 16, 21, 30, 628454)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 16, 21, 30, 628454)),
        ),
    ]
