# Generated by Django 3.0.5 on 2023-05-17 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20230517_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 15, 58, 617406)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 15, 58, 617406)),
        ),
    ]
