# Generated by Django 3.0.5 on 2023-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
